/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "hello-qroma.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(QromaHeartbeat, QromaHeartbeat, AUTO)


PB_BIND(HelloQroma, HelloQroma, AUTO)


PB_BIND(HelloQromaResponse, HelloQromaResponse, AUTO)


PB_BIND(MathProblem, MathProblem, AUTO)


PB_BIND(MathResult_Add, MathResult_Add, AUTO)


PB_BIND(MathResult_Subtract, MathResult_Subtract, AUTO)


PB_BIND(MathResult_AddAndSubtract, MathResult_AddAndSubtract, AUTO)


PB_BIND(MathResponse, MathResponse, AUTO)




