/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_HELLO_QROMA_WITH_STR_RESPONSE_PB_H_INCLUDED
#define PB_HELLO_QROMA_WITH_STR_RESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _HelloQroma { 
    char name[20]; 
} HelloQroma;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HelloQroma_init_default                  {""}
#define HelloQroma_init_zero                     {""}

/* Field tags (for use in manual encoding/decoding) */
#define HelloQroma_name_tag                      1

/* Struct field encoding specification for nanopb */
#define HelloQroma_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define HelloQroma_CALLBACK NULL
#define HelloQroma_DEFAULT NULL

extern const pb_msgdesc_t HelloQroma_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HelloQroma_fields &HelloQroma_msg

/* Maximum encoded size of messages (where known) */
#define HelloQroma_size                          21

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
