# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello-qroma-with-pb-response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello-qroma-with-pb-response.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"hello-qroma-with-pb-response.proto\"\x1a\n\nHelloQroma\x12\x0c\n\x04name\x18\x01 \x01(\t\"M\n\x12HelloQromaResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x11\n\tcallCount\x18\x02 \x01(\r\x12\x12\n\nnameLength\x18\x03 \x01(\rb\x06proto3'
)




_HELLOQROMA = _descriptor.Descriptor(
  name='HelloQroma',
  full_name='HelloQroma',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HelloQroma.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=64,
)


_HELLOQROMARESPONSE = _descriptor.Descriptor(
  name='HelloQromaResponse',
  full_name='HelloQromaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='HelloQromaResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callCount', full_name='HelloQromaResponse.callCount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nameLength', full_name='HelloQromaResponse.nameLength', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['HelloQroma'] = _HELLOQROMA
DESCRIPTOR.message_types_by_name['HelloQromaResponse'] = _HELLOQROMARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloQroma = _reflection.GeneratedProtocolMessageType('HelloQroma', (_message.Message,), {
  'DESCRIPTOR' : _HELLOQROMA,
  '__module__' : 'hello_qroma_with_pb_response_pb2'
  # @@protoc_insertion_point(class_scope:HelloQroma)
  })
_sym_db.RegisterMessage(HelloQroma)

HelloQromaResponse = _reflection.GeneratedProtocolMessageType('HelloQromaResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOQROMARESPONSE,
  '__module__' : 'hello_qroma_with_pb_response_pb2'
  # @@protoc_insertion_point(class_scope:HelloQromaResponse)
  })
_sym_db.RegisterMessage(HelloQromaResponse)


# @@protoc_insertion_point(module_scope)
