#!/bin/bash

echo "Creating output directories"

mkdir outfiles
mkdir outfiles/nanopb
mkdir outfiles/python
mkdir outfiles/dart
mkdir outfiles/typescript

echo "Compiling protobuf files"

cd /usr/src/app/protofiles
# ../generator/generator-bin/protoc *.proto --plugin=protoc-gen-dart=/root/.pub-cache/bin/protoc-gen-dart --nanopb_out=../outfiles/nanopb --python_out=../outfiles/python --dart_out=../outfiles/dart 

TS_OUT_DIR="../outfiles/typescript"

../generator/generator-bin/protoc \
    --js_out=import_style=commonjs,binary \
    *.proto

# ../generator/generator-bin/protoc \
#     --plugin="/usr/src/app/node_modules/.bin/protoc-gen-ts" \
#     --ts_out="${TS_OUT_DIR}" \
#     *.proto

    # --js_out="import_style=commonjs,binary:${TS_OUT_DIR}" \
    # --ts_proto_opt=esModuleInterop=true \


# npx protoc --ts_out ../outfiles/typescript \
#     --proto_path /usr/src/app/protofiles \
#     /usr/src/app/protofiles/*.proto \
#     --experimental_allow_proto3_optional \
#     --ts_opt use_proto_field_name \
#     --ts_opt generate_dependencies

echo "Protobuf files compiled/generated by 'docker-protobuf-compile' using docker image qroma-protobuf-compiler on " $(date) >> ../outfiles/compiled-by-qroma.txt
