# all directories in this file are located relative to the project root
[qroma.project]
name = "qroma-monitor"
# use semantic versioning - see https://en.wikipedia.org/wiki/Software_versioning [Semantic versioning]
version = "0.1.0"


[qroma.project.firmware]
platforms = [
  "arduino",
  "platformio",
]


[qroma.project.run.commands.firmware.platformio]
build = "run"
install = "run --target upload --environment esp32dev"
monitor = ""


[qroma.project.stages.sw.protobuf]
root_dir = "protobufs"
compilers = [
  "nanopb",
  "python",
  "typescript",
  "dart",
]

[[qroma.project.stages.sw.protobuf.sources]]
source_path = "protofiles-in"
dest_path = "protofiles-out"
site_path = "proto"


[qroma.project.stages.sw.protobuf.replication]
nanopb.dirs = ["firmware/esp32/qroma-monitor/src/qroma-proto", ]
python.dirs = ["apps/py-qroma-io/qroma_proto", ]
typescript.dirs = ["sites/site-www-qroma-monitor/src/qroma-proto", ]
dart.dirs = []


[qroma.project.stages.sw.firmware]
project_dirs = []


[qroma.project.stages.sw.apps]
project_dirs = []


[qroma.project.stages.sw.sites]
project_dirs = []


[qroma.project.stages.sw.sites.bundle]
bundle_static_dir="sites/site-www-qroma-monitor/static"
bundle_version_content_root_dir_template="{bundle_root_path}/qroma/versions"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="firmware/esp32/qroma-monitor/.pio/build/esp32dev/firmware.bin"
publication_filepath="firmware/firmware.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="firmware/esp32/qroma-monitor/.pio/build/esp32dev/bootloader.bin"
publication_filepath="firmware/bootloader.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="firmware/esp32/qroma-monitor/.pio/build/esp32dev/partitions.bin"
publication_filepath="firmware/partitions.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="C:/Users/ajb/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin"
publication_filepath="firmware/boot_app0.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.zipped_dirs]]
source_dir="protobufs/protofiles-out"
publication_zip_file="protobufs.zip"


[[qroma.project.stages.sw.sites.bundle.publish_version.generated_files]]
publication_filepath="firmware/manifest-firmware.json"
template_str="""{
  "name": "qroma-monitor",
  "version": "esp32",
  "builds": [
    {
      "chipFamily": "ESP32",
      "parts": [
        { "path": "bootloader.bin", "offset": 4096 },
        { "path": "partitions.bin", "offset": 32768 },
        { "path": "boot_app0.bin", "offset": 57344 },
        { "path": "firmware.bin", "offset": 65536 }
      ]
    }
  ]
}
"""