/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "hello-qroma-with-pb-response.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HelloQroma, HelloQroma, AUTO)


PB_BIND(HelloQromaResponse, HelloQromaResponse, AUTO)



